### ISSUE TITLE
Fail to build val dataloader

### ISSUE THREAD

**Issue by fuqianya** [facebookresearch/KeypointNeRF#3]
Hi, authors,

Thanks for your great works! I'm interesting with the performance of KeypointNeRF on the ZJU dataset. I follow the [DATA_PREP](https://github.com/facebookresearch/KeypointNeRF/blob/main/DATA_PREP.md) to prepare dataset and start to train KeypointNeRF.

However, I had the following error:
![1660637435(1)](https://user-images.githubusercontent.com/45023083/184830616-29d15688-c65b-4b9e-84df-7eda505dd413.jpg)

This is caused when I built the val or test dataset. I had checked the code and found the reason:

I notice that CoreView313 and CoreView315 use different sampled cameras with other persons, see [here](https://github.com/facebookresearch/KeypointNeRF/blob/main/src/zju_dataset.py#L41). The number of cameras in the CoreView 313 and CoreView 315 are 21, so the index of 21 at [here](https://github.com/facebookresearch/KeypointNeRF/blob/main/src/zju_dataset.py#L97) is out of bounds.

Could plz to check this for me?

**Comment by markomih** [comment]
Hi Fuqianya, thank you for reporting the issue! 

We use only these [three subjects](https://github.com/facebookresearch/KeypointNeRF/blob/main/src/zju_dataset.py#L30) (CoreView_387, CoreView_393, CoreView_394)  for evaluation. 

Have you by chance selected one of the training subjects in the val/test data loader?

**Comment by fuqianya** [comment]
Oh, yes. Thanks for your quick rely!

It's my mistake. Since I only download the CoreView313, so I evaluate on it. This issue can be fixed by not performing evaluation on the CoreView313 and 315.

I have another problem: How many gpu times are used for training on the ZJU-MOCAP? And which gpu are your used? I had tried on my 3090, but it failed due to the limited gpu memory.

**Comment by fuqianya** [comment]
All right, thanks~

I have evaluate the pretrained model on my 3090 successfully..

How about the training time? How many gpus are you used for training?

**Comment by markomih** [comment]
We used only 1 GPU. 
The multi-gpu training is supported as well.

**Comment by fuqianya** [comment]
ok, thanks for your rely! I will close this issue.
