### ISSUE TITLE
How to generate 3D joints files

### ISSUE THREAD

**Issue by fuqianya** [facebookresearch/KeypointNeRF#4]
Hi, authors

which tool are you used to generate the zju_joints3d.zip?

I am trying to train KeypointNeRF on my own dataset.

**Comment by fuqianya** [comment]
Could you kindly to provide your scripts to generate 3D joints files?

**Comment by markomih** [comment]
Hi, you could use [EasyMocap](https://github.com/zju3dv/EasyMocap) to obtain 3D bodies and extract their joints or directly use openpose to extract keypoints and uplifting them via [triangulation](https://kornia.readthedocs.io/en/latest/_modules/kornia/geometry/epipolar/triangulation.html). 
The former approach will provide better quality, while the latter is faster.
