### ISSUE TITLE
reconstruction of human heads

### ISSUE THREAD

**Issue by CCOSerika** [facebookresearch/KeypointNeRF#5]
Hi, author. Thanx for your great work!
It seems that the example given is on task of reconstruction of human bodies. I wonder how to reconstruct human heads from two or three images. 
Maybe I read it wrong. Look forwarding to your reply!

**Comment by markomih** [comment]
Hi CCOSerika, thank you. 
We have released the training code and the pre-trained model only for the reconstruction of full human bodies. 
The model on heads is trained on internal data, thus we cannot release it. However, with the provided code you could train the model on heads too.

**Comment by CCOSerika** [comment]
I see. I'll try it. Thank you for the response!

**Comment by YiChenCityU** [comment]
> Hi CCOSerika, thank you. We have released the training code and the pre-trained model only for the reconstruction of full human bodies. The model on heads is trained on internal data, thus we cannot release it. However, with the provided code you could train the model on heads too.

The body nerf needs precalculated 3D joints. Did I have to input precalculated keypoints of face as well? Thanks very much.

**Comment by markomih** [comment]
Yes, the precalculated keypoints are required for human faces too.

**Comment by ohjarwa** [comment]
> > Hi CCOSerika, thank you. We have released the training code and the pre-trained model only for the reconstruction of full human bodies. The model on heads is trained on internal data, thus we cannot release it. However, with the provided code you could train the model on heads too.
> 
> The body nerf needs precalculated 3D joints. Did I have to input precalculated keypoints of face as well? Thanks very much.

Hi！Have you apply keypointnerf on human face？If so, can I ask some questions to you? Thank you.
