### ISSUE TITLE
GPU memory usage on more images?

### ISSUE THREAD

**Issue by hengfei-wang** [facebookresearch/KeypointNeRF#6]
Hi,

Thank you for releasing the code.

I wonder how much GPU memory KeypointNeRF requires if I use more images like 16 images. Since keypointnerf needs to keep feature maps of all imput images, I want to know if 24GB GPU memory is enough for the training.

Thanks

**Comment by markomih** [comment]
Hi @hengfei-wang, 
we haven't tried to use more than 3-4 images. However, you could still use fewer images (e.g 4) during the training if the memory is an issue.
Using 16 images at inference time should fit into a 24GB GPU memory as long as you use a small number of sampled rays per batch.
