### ISSUE TITLE
Render on my own data

### ISSUE THREAD

**Issue by StefanZt** [facebookresearch/KeypointNeRF#7]
Hi, author. Thanks for your great work!

I'm trying to use your pre-trained model to render my own data, but the function "decode_batch" and the parameters "batch" seems too complicate for me. I'm wondering if there is some easy way to do it?

Look forwarding to your reply!

**Comment by markomih** [comment]
Hi @StefanZt, thanks for the question! 

We don't have plans to release a simpler interface in the near future. However, if you create one, please make a pull request. We would be happy to integrate it into our project.
