### ISSUE TITLE
Render on synthetic dataset

### ISSUE THREAD

**Issue by Takeda1934** [facebookresearch/KeypointNeRF#8]
Hello, thanks for this great work!

I want to try this method on NeRF synthetic dataset (https://drive.google.com/drive/folders/1JDdLGDruGNXWnM1eqY1FNL9PlStjaKWi).

Is this method applicable to non-human data?

**Comment by markomih** [comment]
Hi @Takeda1934, this work is suited for objects with consistent key points and cannot be directly applied to the NeRF synthetic dataset without significant modifications.
