### ISSUE TITLE
dataset error

### ISSUE THREAD

**Issue by liwenssss** [facebookresearch/KeypointNeRF#9]
Hi, thanks for your nice work. I download zju_mocap dataset but I dont find CoreView_396 as mentioned in your dataset.
![image](https://user-images.githubusercontent.com/11902259/194733017-4d806399-a030-4b9b-a290-bdd24648e745.png)

**Comment by markomih** [comment]
Hi @liwenssss, I think you are using a different subset of the dataset (one that was used in Animatable NeRF). We use the original neural body dataset with the following structure: 
![image](https://user-images.githubusercontent.com/13746017/194758216-5a7815a3-ea7a-49f2-b432-441f926d3149.png)

**Comment by liwenssss** [comment]
Hi @markomih ,Thanks for your reply. Another question, I want to know how much GPU memory doed it need when training? I didn't change anything but I got "out of memory" on a RTX3090..

**Comment by markomih** [comment]
Hi @liwenssss, the default training setting takes around 30GB. 
However, lowering the resolution of the rendered patch would decrease memory consumption with very little performance degradation. 
I'd suggest setting train_out_h and train_out_w to 48 (or 32 if still doesn't fit) in the config file ([here](https://github.com/facebookresearch/KeypointNeRF/blob/main/configs/zju.json#L36)) for a 24GB GPU.

**Comment by XiaoliNolan** [comment]
Hi @markomih, I use the original neural body dataset to test the code. I met this problem "FileNotFoundError: [Errno 2] No such file or directory: './data/zju_mocap/CoreView_387/joints3d/0.npy'". How can I get the joints3d folder? Thanks.
